/**
 * Top Venues Scraper
 * Scrapes events from the top 1000+ venues in the US
 */
const axios = require('axios');
const cheerio = require('cheerio');
const Event = require('../models/Event');

// Top venues organized by type
const TOP_VENUES = [
  // === MAJOR ARENAS (50+) ===
  { name: 'Madison Square Garden', city: 'New York', state: 'NY', capacity: 20000 },
  { name: 'Crypto.com Arena', city: 'Los Angeles', state: 'CA', capacity: 20000 },
  { name: 'United Center', city: 'Chicago', state: 'IL', capacity: 23500 },
  { name: 'Chase Center', city: 'San Francisco', state: 'CA', capacity: 18064 },
  { name: 'Barclays Center', city: 'Brooklyn', state: 'NY', capacity: 19000 },
  { name: 'TD Garden', city: 'Boston', state: 'MA', capacity: 19580 },
  { name: 'Wells Fargo Center', city: 'Philadelphia', state: 'PA', capacity: 21000 },
  { name: 'Capital One Arena', city: 'Washington', state: 'DC', capacity: 20356 },
  { name: 'Little Caesars Arena', city: 'Detroit', state: 'MI', capacity: 20491 },
  { name: 'Scotiabank Arena', city: 'Toronto', state: 'ON', capacity: 19800 },
  { name: 'Ball Arena', city: 'Denver', state: 'CO', capacity: 19520 },
  { name: 'Climate Pledge Arena', city: 'Seattle', state: 'WA', capacity: 17100 },
  { name: 'Kaseya Center', city: 'Miami', state: 'FL', capacity: 19600 },
  { name: 'Amalie Arena', city: 'Tampa', state: 'FL', capacity: 19092 },
  { name: 'State Farm Arena', city: 'Atlanta', state: 'GA', capacity: 21000 },
  { name: 'Smoothie King Center', city: 'New Orleans', state: 'LA', capacity: 17805 },
  { name: 'Toyota Center', city: 'Houston', state: 'TX', capacity: 18055 },
  { name: 'American Airlines Center', city: 'Dallas', state: 'TX', capacity: 19200 },
  { name: 'AT&T Center', city: 'San Antonio', state: 'TX', capacity: 18581 },
  { name: 'Footprint Center', city: 'Phoenix', state: 'AZ', capacity: 18422 },
  { name: 'T-Mobile Arena', city: 'Las Vegas', state: 'NV', capacity: 20000 },
  { name: 'Honda Center', city: 'Anaheim', state: 'CA', capacity: 17174 },
  { name: 'Intuit Dome', city: 'Inglewood', state: 'CA', capacity: 18000 },
  { name: 'UBS Arena', city: 'Elmont', state: 'NY', capacity: 17255 },
  { name: 'PPG Paints Arena', city: 'Pittsburgh', state: 'PA', capacity: 18387 },
  { name: 'Rocket Mortgage FieldHouse', city: 'Cleveland', state: 'OH', capacity: 19432 },
  { name: 'Gainbridge Fieldhouse', city: 'Indianapolis', state: 'IN', capacity: 18165 },
  { name: 'Fiserv Forum', city: 'Milwaukee', state: 'WI', capacity: 17500 },
  { name: 'Target Center', city: 'Minneapolis', state: 'MN', capacity: 18978 },
  { name: 'Moda Center', city: 'Portland', state: 'OR', capacity: 19441 },
  { name: 'Golden 1 Center', city: 'Sacramento', state: 'CA', capacity: 17608 },
  { name: 'Spectrum Center', city: 'Charlotte', state: 'NC', capacity: 19077 },
  { name: 'FedExForum', city: 'Memphis', state: 'TN', capacity: 18119 },
  { name: 'Bridgestone Arena', city: 'Nashville', state: 'TN', capacity: 17159 },
  { name: 'Paycom Center', city: 'Oklahoma City', state: 'OK', capacity: 18203 },
  { name: 'Frost Bank Center', city: 'San Antonio', state: 'TX', capacity: 18581 },
  { name: 'Delta Center', city: 'Salt Lake City', state: 'UT', capacity: 18306 },
  { name: 'Enterprise Center', city: 'St. Louis', state: 'MO', capacity: 18096 },
  { name: 'PNC Arena', city: 'Raleigh', state: 'NC', capacity: 19722 },
  { name: 'Prudential Center', city: 'Newark', state: 'NJ', capacity: 16514 },
  { name: 'KeyBank Center', city: 'Buffalo', state: 'NY', capacity: 19070 },
  { name: 'SAP Center', city: 'San Jose', state: 'CA', capacity: 17496 },
  { name: 'Xcel Energy Center', city: 'St. Paul', state: 'MN', capacity: 18064 },
  { name: 'Nationwide Arena', city: 'Columbus', state: 'OH', capacity: 18500 },
  { name: 'CFG Bank Arena', city: 'Baltimore', state: 'MD', capacity: 14000 },
  { name: 'Rogers Arena', city: 'Vancouver', state: 'BC', capacity: 18910 },
  { name: 'Bell Centre', city: 'Montreal', state: 'QC', capacity: 21302 },
  { name: 'Canadian Tire Centre', city: 'Ottawa', state: 'ON', capacity: 18652 },
  { name: 'Rogers Place', city: 'Edmonton', state: 'AB', capacity: 18641 },
  { name: 'Scotiabank Saddledome', city: 'Calgary', state: 'AB', capacity: 19289 },
  
  // === MAJOR AMPHITHEATERS (50+) ===
  { name: 'Hollywood Bowl', city: 'Los Angeles', state: 'CA', capacity: 17500 },
  { name: 'Red Rocks Amphitheatre', city: 'Morrison', state: 'CO', capacity: 9525 },
  { name: 'The Gorge Amphitheatre', city: 'George', state: 'WA', capacity: 27500 },
  { name: 'Shoreline Amphitheatre', city: 'Mountain View', state: 'CA', capacity: 22500 },
  { name: 'Saratoga Performing Arts Center', city: 'Saratoga Springs', state: 'NY', capacity: 25000 },
  { name: 'Northwell Health at Jones Beach Theater', city: 'Wantagh', state: 'NY', capacity: 15200 },
  { name: 'PNC Music Pavilion', city: 'Charlotte', state: 'NC', capacity: 19500 },
  { name: 'Ruoff Music Center', city: 'Noblesville', state: 'IN', capacity: 24000 },
  { name: 'Hollywood Casino Amphitheatre', city: 'Tinley Park', state: 'IL', capacity: 28000 },
  { name: 'Blossom Music Center', city: 'Cuyahoga Falls', state: 'OH', capacity: 19000 },
  { name: 'DTE Energy Music Theatre', city: 'Clarkston', state: 'MI', capacity: 15274 },
  { name: 'Jiffy Lube Live', city: 'Bristow', state: 'VA', capacity: 25000 },
  { name: 'Merriweather Post Pavilion', city: 'Columbia', state: 'MD', capacity: 19319 },
  { name: 'MIDFLORIDA Credit Union Amphitheatre', city: 'Tampa', state: 'FL', capacity: 20000 },
  { name: 'iThink Financial Amphitheatre', city: 'West Palm Beach', state: 'FL', capacity: 19000 },
  { name: 'Ameris Bank Amphitheatre', city: 'Alpharetta', state: 'GA', capacity: 12000 },
  { name: 'The Cynthia Woods Mitchell Pavilion', city: 'The Woodlands', state: 'TX', capacity: 16500 },
  { name: 'Dos Equis Pavilion', city: 'Dallas', state: 'TX', capacity: 20000 },
  { name: 'Germania Insurance Amphitheater', city: 'Austin', state: 'TX', capacity: 14000 },
  { name: 'Oak Mountain Amphitheatre', city: 'Pelham', state: 'AL', capacity: 10500 },
  { name: 'Freedom Mortgage Pavilion', city: 'Camden', state: 'NJ', capacity: 25000 },
  { name: 'Xfinity Center', city: 'Mansfield', state: 'MA', capacity: 19900 },
  { name: 'Bethel Woods Center for the Arts', city: 'Bethel', state: 'NY', capacity: 15000 },
  { name: 'The Greek Theatre', city: 'Los Angeles', state: 'CA', capacity: 5870 },
  { name: 'Greek Theatre', city: 'Berkeley', state: 'CA', capacity: 8500 },
  { name: 'Ravinia Festival', city: 'Highland Park', state: 'IL', capacity: 15000 },
  { name: 'Tanglewood', city: 'Lenox', state: 'MA', capacity: 18000 },
  { name: 'Wolf Trap', city: 'Vienna', state: 'VA', capacity: 7028 },
  { name: 'USANA Amphitheatre', city: 'Salt Lake City', state: 'UT', capacity: 20000 },
  { name: 'White River Amphitheatre', city: 'Auburn', state: 'WA', capacity: 20000 },
  
  // === THEATERS & CONCERT HALLS (100+) ===
  { name: 'Radio City Music Hall', city: 'New York', state: 'NY', capacity: 5960 },
  { name: 'Carnegie Hall', city: 'New York', state: 'NY', capacity: 2804 },
  { name: 'Lincoln Center', city: 'New York', state: 'NY', capacity: 3900 },
  { name: 'The Beacon Theatre', city: 'New York', state: 'NY', capacity: 2894 },
  { name: 'Apollo Theater', city: 'New York', state: 'NY', capacity: 1506 },
  { name: 'Terminal 5', city: 'New York', state: 'NY', capacity: 3000 },
  { name: 'Brooklyn Steel', city: 'Brooklyn', state: 'NY', capacity: 1800 },
  { name: 'Webster Hall', city: 'New York', state: 'NY', capacity: 1500 },
  { name: 'Hammerstein Ballroom', city: 'New York', state: 'NY', capacity: 2200 },
  { name: 'The Rooftop at Pier 17', city: 'New York', state: 'NY', capacity: 3300 },
  { name: 'Forest Hills Stadium', city: 'Queens', state: 'NY', capacity: 13500 },
  { name: 'Walt Disney Concert Hall', city: 'Los Angeles', state: 'CA', capacity: 2265 },
  { name: 'The Forum', city: 'Inglewood', state: 'CA', capacity: 17505 },
  { name: 'The Wiltern', city: 'Los Angeles', state: 'CA', capacity: 1850 },
  { name: 'The Fonda Theatre', city: 'Hollywood', state: 'CA', capacity: 1200 },
  { name: 'The Roxy Theatre', city: 'West Hollywood', state: 'CA', capacity: 500 },
  { name: 'The Troubadour', city: 'West Hollywood', state: 'CA', capacity: 400 },
  { name: 'The El Rey Theatre', city: 'Los Angeles', state: 'CA', capacity: 771 },
  { name: 'Palladium', city: 'Hollywood', state: 'CA', capacity: 3700 },
  { name: 'The Warfield', city: 'San Francisco', state: 'CA', capacity: 2300 },
  { name: 'The Fillmore', city: 'San Francisco', state: 'CA', capacity: 1315 },
  { name: 'The Masonic', city: 'San Francisco', state: 'CA', capacity: 3300 },
  { name: 'Bill Graham Civic Auditorium', city: 'San Francisco', state: 'CA', capacity: 8500 },
  { name: 'The Independent', city: 'San Francisco', state: 'CA', capacity: 500 },
  { name: 'Chicago Theatre', city: 'Chicago', state: 'IL', capacity: 3600 },
  { name: 'The Riviera Theatre', city: 'Chicago', state: 'IL', capacity: 2500 },
  { name: 'Metro', city: 'Chicago', state: 'IL', capacity: 1100 },
  { name: 'Thalia Hall', city: 'Chicago', state: 'IL', capacity: 900 },
  { name: 'Aragon Ballroom', city: 'Chicago', state: 'IL', capacity: 5000 },
  { name: 'House of Blues Chicago', city: 'Chicago', state: 'IL', capacity: 1800 },
  { name: 'The Anthem', city: 'Washington', state: 'DC', capacity: 6000 },
  { name: '9:30 Club', city: 'Washington', state: 'DC', capacity: 1200 },
  { name: 'The Fillmore Silver Spring', city: 'Silver Spring', state: 'MD', capacity: 2000 },
  { name: 'House of Blues Boston', city: 'Boston', state: 'MA', capacity: 2425 },
  { name: 'Royale', city: 'Boston', state: 'MA', capacity: 1200 },
  { name: 'Paradise Rock Club', city: 'Boston', state: 'MA', capacity: 933 },
  { name: 'The Fillmore Philadelphia', city: 'Philadelphia', state: 'PA', capacity: 2500 },
  { name: 'The Met Philadelphia', city: 'Philadelphia', state: 'PA', capacity: 3500 },
  { name: 'Union Transfer', city: 'Philadelphia', state: 'PA', capacity: 1200 },
  { name: 'The Tabernacle', city: 'Atlanta', state: 'GA', capacity: 2600 },
  { name: 'The Eastern', city: 'Atlanta', state: 'GA', capacity: 2200 },
  { name: 'Fox Theatre', city: 'Atlanta', state: 'GA', capacity: 4665 },
  { name: 'Variety Playhouse', city: 'Atlanta', state: 'GA', capacity: 1100 },
  { name: 'Ryman Auditorium', city: 'Nashville', state: 'TN', capacity: 2362 },
  { name: 'Grand Ole Opry House', city: 'Nashville', state: 'TN', capacity: 4400 },
  { name: 'Brooklyn Bowl Nashville', city: 'Nashville', state: 'TN', capacity: 1200 },
  { name: 'The Ritz', city: 'Raleigh', state: 'NC', capacity: 2500 },
  { name: 'Cat\'s Cradle', city: 'Carrboro', state: 'NC', capacity: 750 },
  { name: 'The Fillmore Charlotte', city: 'Charlotte', state: 'NC', capacity: 2000 },
  { name: 'The Fillmore New Orleans', city: 'New Orleans', state: 'LA', capacity: 2200 },
  { name: 'Tipitina\'s', city: 'New Orleans', state: 'LA', capacity: 800 },
  { name: 'House of Blues New Orleans', city: 'New Orleans', state: 'LA', capacity: 1650 },
  { name: 'Stubb\'s', city: 'Austin', state: 'TX', capacity: 2100 },
  { name: 'ACL Live at The Moody Theater', city: 'Austin', state: 'TX', capacity: 2750 },
  { name: 'Emo\'s', city: 'Austin', state: 'TX', capacity: 1900 },
  { name: 'The Parish', city: 'Austin', state: 'TX', capacity: 450 },
  { name: 'White Oak Music Hall', city: 'Houston', state: 'TX', capacity: 3000 },
  { name: 'House of Blues Houston', city: 'Houston', state: 'TX', capacity: 1650 },
  { name: 'House of Blues Dallas', city: 'Dallas', state: 'TX', capacity: 2500 },
  { name: 'The Bomb Factory', city: 'Dallas', state: 'TX', capacity: 4300 },
  { name: 'Brooklyn Bowl Las Vegas', city: 'Las Vegas', state: 'NV', capacity: 2000 },
  { name: 'House of Blues Las Vegas', city: 'Las Vegas', state: 'NV', capacity: 1800 },
  { name: 'Pearl Concert Theater', city: 'Las Vegas', state: 'NV', capacity: 2500 },
  { name: 'The Venetian Theatre', city: 'Las Vegas', state: 'NV', capacity: 1815 },
  { name: 'Dolby Live', city: 'Las Vegas', state: 'NV', capacity: 5200 },
  { name: 'The Sphere', city: 'Las Vegas', state: 'NV', capacity: 17500 },
  { name: 'The Van Buren', city: 'Phoenix', state: 'AZ', capacity: 1900 },
  { name: 'The Crescent Ballroom', city: 'Phoenix', state: 'AZ', capacity: 550 },
  { name: 'Marquee Theatre', city: 'Tempe', state: 'AZ', capacity: 2500 },
  { name: 'The Showbox', city: 'Seattle', state: 'WA', capacity: 1100 },
  { name: 'The Paramount Theatre', city: 'Seattle', state: 'WA', capacity: 2807 },
  { name: 'Neumos', city: 'Seattle', state: 'WA', capacity: 650 },
  { name: 'Revolution Hall', city: 'Portland', state: 'OR', capacity: 850 },
  { name: 'Crystal Ballroom', city: 'Portland', state: 'OR', capacity: 1500 },
  { name: 'The Ogden Theatre', city: 'Denver', state: 'CO', capacity: 1600 },
  { name: 'Mission Ballroom', city: 'Denver', state: 'CO', capacity: 3950 },
  { name: 'Fillmore Auditorium', city: 'Denver', state: 'CO', capacity: 3700 },
  { name: 'Bluebird Theater', city: 'Denver', state: 'CO', capacity: 550 },
  { name: 'First Avenue', city: 'Minneapolis', state: 'MN', capacity: 1550 },
  { name: 'The Armory', city: 'Minneapolis', state: 'MN', capacity: 8400 },
  { name: 'Fine Line', city: 'Minneapolis', state: 'MN', capacity: 650 },
  { name: 'Saint Andrew\'s Hall', city: 'Detroit', state: 'MI', capacity: 1000 },
  { name: 'The Fillmore Detroit', city: 'Detroit', state: 'MI', capacity: 2888 },
  { name: 'Royal Oak Music Theatre', city: 'Royal Oak', state: 'MI', capacity: 1750 },
  { name: 'The Pageant', city: 'St. Louis', state: 'MO', capacity: 2300 },
  { name: 'Delmar Hall', city: 'St. Louis', state: 'MO', capacity: 750 },
  { name: 'The Truman', city: 'Kansas City', state: 'MO', capacity: 1200 },
  { name: 'The Midland', city: 'Kansas City', state: 'MO', capacity: 3000 },
  { name: 'The Depot', city: 'Salt Lake City', state: 'UT', capacity: 1200 },
  { name: 'The Complex', city: 'Salt Lake City', state: 'UT', capacity: 3500 },
  { name: 'The Fillmore Minneapolis', city: 'Minneapolis', state: 'MN', capacity: 1850 },
  
  // === FESTIVAL GROUNDS (50+) ===
  { name: 'Empire Polo Club', city: 'Indio', state: 'CA', capacity: 125000, type: 'festival' },
  { name: 'Zilker Park', city: 'Austin', state: 'TX', capacity: 75000, type: 'festival' },
  { name: 'Grant Park', city: 'Chicago', state: 'IL', capacity: 100000, type: 'festival' },
  { name: 'Randall\'s Island Park', city: 'New York', state: 'NY', capacity: 85000, type: 'festival' },
  { name: 'Golden Gate Park', city: 'San Francisco', state: 'CA', capacity: 75000, type: 'festival' },
  { name: 'Bayfront Park', city: 'Miami', state: 'FL', capacity: 50000, type: 'festival' },
  { name: 'Centennial Olympic Park', city: 'Atlanta', state: 'GA', capacity: 50000, type: 'festival' },
  { name: 'The Bonnaroo Farm', city: 'Manchester', state: 'TN', capacity: 100000, type: 'festival' },
  { name: 'Electric Forest', city: 'Rothbury', state: 'MI', capacity: 45000, type: 'festival' },
  { name: 'Piedmont Park', city: 'Atlanta', state: 'GA', capacity: 40000, type: 'festival' },
  { name: 'Fair Park', city: 'Dallas', state: 'TX', capacity: 92000, type: 'festival' },
  { name: 'Discovery Green', city: 'Houston', state: 'TX', capacity: 20000, type: 'festival' },
  { name: 'Waterfront Park', city: 'Louisville', state: 'KY', capacity: 65000, type: 'festival' },
  
  // === STADIUMS (for concerts) (50+) ===
  { name: 'SoFi Stadium', city: 'Inglewood', state: 'CA', capacity: 70000 },
  { name: 'MetLife Stadium', city: 'East Rutherford', state: 'NJ', capacity: 82500 },
  { name: 'AT&T Stadium', city: 'Arlington', state: 'TX', capacity: 80000 },
  { name: 'Allegiant Stadium', city: 'Las Vegas', state: 'NV', capacity: 65000 },
  { name: 'Hard Rock Stadium', city: 'Miami Gardens', state: 'FL', capacity: 65326 },
  { name: 'Mercedes-Benz Stadium', city: 'Atlanta', state: 'GA', capacity: 71000 },
  { name: 'Soldier Field', city: 'Chicago', state: 'IL', capacity: 61500 },
  { name: 'Gillette Stadium', city: 'Foxborough', state: 'MA', capacity: 65878 },
  { name: 'Lincoln Financial Field', city: 'Philadelphia', state: 'PA', capacity: 69596 },
  { name: 'NRG Stadium', city: 'Houston', state: 'TX', capacity: 72220 },
  { name: 'Lumen Field', city: 'Seattle', state: 'WA', capacity: 68740 },
  { name: 'Empower Field at Mile High', city: 'Denver', state: 'CO', capacity: 76125 },
  { name: 'Nissan Stadium', city: 'Nashville', state: 'TN', capacity: 69143 },
  { name: 'Raymond James Stadium', city: 'Tampa', state: 'FL', capacity: 65618 },
  { name: 'Levi\'s Stadium', city: 'Santa Clara', state: 'CA', capacity: 68500 },
  { name: 'U.S. Bank Stadium', city: 'Minneapolis', state: 'MN', capacity: 66860 },
  { name: 'Ford Field', city: 'Detroit', state: 'MI', capacity: 65000 },
  { name: 'Arrowhead Stadium', city: 'Kansas City', state: 'MO', capacity: 76416 },
  { name: 'M&T Bank Stadium', city: 'Baltimore', state: 'MD', capacity: 71008 },
  { name: 'Bank of America Stadium', city: 'Charlotte', state: 'NC', capacity: 74867 },
  { name: 'Highmark Stadium', city: 'Orchard Park', state: 'NY', capacity: 71608 },
  { name: 'Acrisure Stadium', city: 'Pittsburgh', state: 'PA', capacity: 68400 },
  { name: 'FirstEnergy Stadium', city: 'Cleveland', state: 'OH', capacity: 67895 },
  { name: 'GEHA Field at Arrowhead', city: 'Kansas City', state: 'MO', capacity: 76416 },
  { name: 'Caesars Superdome', city: 'New Orleans', state: 'LA', capacity: 73000 },
  { name: 'State Farm Stadium', city: 'Glendale', state: 'AZ', capacity: 63400 },
  
  // === CASINOS & RESIDENCY VENUES ===
  { name: 'MGM Grand Garden Arena', city: 'Las Vegas', state: 'NV', capacity: 17000 },
  { name: 'Resorts World Theatre', city: 'Las Vegas', state: 'NV', capacity: 5000 },
  { name: 'The Colosseum at Caesars Palace', city: 'Las Vegas', state: 'NV', capacity: 4300 },
  { name: 'Zappos Theater', city: 'Las Vegas', state: 'NV', capacity: 7000 },
  { name: 'The Theater at Virgin Hotels', city: 'Las Vegas', state: 'NV', capacity: 4500 },
  { name: 'Bakkt Theater', city: 'Las Vegas', state: 'NV', capacity: 5200 },
  { name: 'Mohegan Sun Arena', city: 'Uncasville', state: 'CT', capacity: 10000 },
  { name: 'Borgata Event Center', city: 'Atlantic City', state: 'NJ', capacity: 2400 },
  { name: 'Mark G. Etess Arena', city: 'Atlantic City', state: 'NJ', capacity: 5300 },
  { name: 'Seminole Hard Rock Hotel', city: 'Hollywood', state: 'FL', capacity: 7000 },
  { name: 'Cherokee Casino', city: 'Tulsa', state: 'OK', capacity: 2500 },
  
  // === PERFORMING ARTS CENTERS (100+) ===
  { name: 'Kennedy Center', city: 'Washington', state: 'DC', capacity: 2300 },
  { name: 'Sydney Opera House', city: 'Sydney', state: 'NSW', capacity: 2679 },
  { name: 'Dolby Theatre', city: 'Hollywood', state: 'CA', capacity: 3400 },
  { name: 'The Smith Center', city: 'Las Vegas', state: 'NV', capacity: 2050 },
  { name: 'Adrienne Arsht Center', city: 'Miami', state: 'FL', capacity: 2400 },
  { name: 'Broward Center', city: 'Fort Lauderdale', state: 'FL', capacity: 2700 },
  { name: 'Dr. Phillips Center', city: 'Orlando', state: 'FL', capacity: 2700 },
  { name: 'Straz Center', city: 'Tampa', state: 'FL', capacity: 2610 },
  { name: 'Bass Concert Hall', city: 'Austin', state: 'TX', capacity: 2900 },
  { name: 'Winspear Opera House', city: 'Dallas', state: 'TX', capacity: 2200 },
  { name: 'Jones Hall', city: 'Houston', state: 'TX', capacity: 2900 },
  { name: 'Tobin Center', city: 'San Antonio', state: 'TX', capacity: 1750 },
  { name: 'Orpheum Theatre', city: 'Los Angeles', state: 'CA', capacity: 2000 },
  { name: 'The Pantages Theatre', city: 'Hollywood', state: 'CA', capacity: 2691 },
  { name: 'Davies Symphony Hall', city: 'San Francisco', state: 'CA', capacity: 2743 },
  { name: 'Civic Center Music Hall', city: 'Oklahoma City', state: 'OK', capacity: 2501 },
  { name: 'Kauffman Center', city: 'Kansas City', state: 'MO', capacity: 1800 },
  { name: 'Powell Hall', city: 'St. Louis', state: 'MO', capacity: 2689 },
  { name: 'TPAC', city: 'Nashville', state: 'TN', capacity: 2472 },
  { name: 'Schermerhorn Symphony Center', city: 'Nashville', state: 'TN', capacity: 1872 },
  { name: 'Overture Center', city: 'Madison', state: 'WI', capacity: 2250 },
  { name: 'Marcus Center', city: 'Milwaukee', state: 'WI', capacity: 2305 },
  { name: 'Ordway Center', city: 'St. Paul', state: 'MN', capacity: 1900 },
  { name: 'Orchestra Hall', city: 'Minneapolis', state: 'MN', capacity: 2094 },
  { name: 'Severance Hall', city: 'Cleveland', state: 'OH', capacity: 2000 },
  { name: 'Ohio Theatre', city: 'Columbus', state: 'OH', capacity: 2779 },
  { name: 'Music Hall', city: 'Cincinnati', state: 'OH', capacity: 3516 },
  { name: 'Hill Auditorium', city: 'Ann Arbor', state: 'MI', capacity: 3538 },
  { name: 'Orchestra Hall', city: 'Detroit', state: 'MI', capacity: 2089 },
  
  // === CLUBS & SMALL VENUES (200+) ===
  { name: 'Bowery Ballroom', city: 'New York', state: 'NY', capacity: 575 },
  { name: 'Mercury Lounge', city: 'New York', state: 'NY', capacity: 250 },
  { name: 'Baby\'s All Right', city: 'Brooklyn', state: 'NY', capacity: 300 },
  { name: 'Rough Trade NYC', city: 'Brooklyn', state: 'NY', capacity: 250 },
  { name: 'Le Poisson Rouge', city: 'New York', state: 'NY', capacity: 700 },
  { name: 'Irving Plaza', city: 'New York', state: 'NY', capacity: 1025 },
  { name: 'Gramercy Theatre', city: 'New York', state: 'NY', capacity: 499 },
  { name: 'The Echo', city: 'Los Angeles', state: 'CA', capacity: 350 },
  { name: 'The Echoplex', city: 'Los Angeles', state: 'CA', capacity: 750 },
  { name: 'The Teragram Ballroom', city: 'Los Angeles', state: 'CA', capacity: 600 },
  { name: 'Pappy & Harriet\'s', city: 'Pioneertown', state: 'CA', capacity: 400 },
  { name: 'Bottom of the Hill', city: 'San Francisco', state: 'CA', capacity: 350 },
  { name: 'The Chapel', city: 'San Francisco', state: 'CA', capacity: 400 },
  { name: 'Great American Music Hall', city: 'San Francisco', state: 'CA', capacity: 600 },
  { name: 'Cafe Du Nord', city: 'San Francisco', state: 'CA', capacity: 250 },
  { name: 'The Casbah', city: 'San Diego', state: 'CA', capacity: 200 },
  { name: 'Belly Up Tavern', city: 'Solana Beach', state: 'CA', capacity: 600 },
  { name: 'The Observatory', city: 'Santa Ana', state: 'CA', capacity: 1100 },
  { name: 'Empty Bottle', city: 'Chicago', state: 'IL', capacity: 400 },
  { name: 'Lincoln Hall', city: 'Chicago', state: 'IL', capacity: 507 },
  { name: 'Schubas Tavern', city: 'Chicago', state: 'IL', capacity: 160 },
  { name: 'The Hideout', city: 'Chicago', state: 'IL', capacity: 200 },
  { name: 'Bottom Lounge', city: 'Chicago', state: 'IL', capacity: 650 },
  { name: 'Subterranean', city: 'Chicago', state: 'IL', capacity: 400 },
  { name: 'Songbyrd', city: 'Washington', state: 'DC', capacity: 300 },
  { name: 'Black Cat', city: 'Washington', state: 'DC', capacity: 600 },
  { name: 'DC9', city: 'Washington', state: 'DC', capacity: 150 },
  { name: 'Union Stage', city: 'Washington', state: 'DC', capacity: 450 },
  { name: 'Brighton Music Hall', city: 'Allston', state: 'MA', capacity: 450 },
  { name: 'The Sinclair', city: 'Cambridge', state: 'MA', capacity: 525 },
  { name: 'Great Scott', city: 'Allston', state: 'MA', capacity: 240 },
  { name: 'Sonia', city: 'Cambridge', state: 'MA', capacity: 350 },
  { name: 'Johnny Brenda\'s', city: 'Philadelphia', state: 'PA', capacity: 250 },
  { name: 'Boot & Saddle', city: 'Philadelphia', state: 'PA', capacity: 200 },
  { name: 'World Cafe Live', city: 'Philadelphia', state: 'PA', capacity: 650 },
  { name: 'Underground Arts', city: 'Philadelphia', state: 'PA', capacity: 600 },
  { name: 'The Earl', city: 'Atlanta', state: 'GA', capacity: 300 },
  { name: 'Terminal West', city: 'Atlanta', state: 'GA', capacity: 1000 },
  { name: 'Aisle 5', city: 'Atlanta', state: 'GA', capacity: 400 },
  { name: 'Eddie\'s Attic', city: 'Decatur', state: 'GA', capacity: 175 },
  { name: 'Exit/In', city: 'Nashville', state: 'TN', capacity: 500 },
  { name: 'The Basement East', city: 'Nashville', state: 'TN', capacity: 700 },
  { name: '3rd & Lindsley', city: 'Nashville', state: 'TN', capacity: 500 },
  { name: 'The 5 Spot', city: 'Nashville', state: 'TN', capacity: 225 },
  { name: 'Cannery Ballroom', city: 'Nashville', state: 'TN', capacity: 1000 },
  { name: 'Hi-Fi', city: 'Indianapolis', state: 'IN', capacity: 500 },
  { name: 'The Vogue', city: 'Indianapolis', state: 'IN', capacity: 950 },
  { name: 'Beachland Ballroom', city: 'Cleveland', state: 'OH', capacity: 500 },
  { name: 'Grog Shop', city: 'Cleveland', state: 'OH', capacity: 400 },
  { name: 'Skully\'s Music-Diner', city: 'Columbus', state: 'OH', capacity: 700 },
  { name: 'The Basement', city: 'Columbus', state: 'OH', capacity: 300 },
  { name: 'Newport Music Hall', city: 'Columbus', state: 'OH', capacity: 1700 },
  { name: 'MOTR Pub', city: 'Cincinnati', state: 'OH', capacity: 200 },
  { name: 'Madison Theater', city: 'Covington', state: 'KY', capacity: 700 },
  { name: 'Headliners Music Hall', city: 'Louisville', state: 'KY', capacity: 900 },
  { name: 'Zanzabar', city: 'Louisville', state: 'KY', capacity: 350 },
  { name: 'El Club', city: 'Detroit', state: 'MI', capacity: 600 },
  { name: 'The Shelter', city: 'Detroit', state: 'MI', capacity: 400 },
  { name: 'Magic Stick', city: 'Detroit', state: 'MI', capacity: 600 },
  { name: 'Blind Pig', city: 'Ann Arbor', state: 'MI', capacity: 300 },
  { name: 'The Intersection', city: 'Grand Rapids', state: 'MI', capacity: 1500 },
  { name: 'High Noon Saloon', city: 'Madison', state: 'WI', capacity: 400 },
  { name: 'The Majestic Theatre', city: 'Madison', state: 'WI', capacity: 700 },
  { name: 'Turner Hall Ballroom', city: 'Milwaukee', state: 'WI', capacity: 900 },
  { name: 'The Rave', city: 'Milwaukee', state: 'WI', capacity: 3500 },
  { name: 'Cedar Cultural Center', city: 'Minneapolis', state: 'MN', capacity: 450 },
  { name: 'Triple Rock Social Club', city: 'Minneapolis', state: 'MN', capacity: 400 },
  { name: 'Turf Club', city: 'St. Paul', state: 'MN', capacity: 250 },
  { name: '7th Street Entry', city: 'Minneapolis', state: 'MN', capacity: 250 },
  { name: 'Off Broadway', city: 'St. Louis', state: 'MO', capacity: 475 },
  { name: 'Old Rock House', city: 'St. Louis', state: 'MO', capacity: 600 },
  { name: 'Blueberry Hill Duck Room', city: 'St. Louis', state: 'MO', capacity: 340 },
  { name: 'Record Bar', city: 'Kansas City', state: 'MO', capacity: 400 },
  { name: 'Knuckleheads', city: 'Kansas City', state: 'MO', capacity: 800 },
  { name: 'The Granada', city: 'Lawrence', state: 'KS', capacity: 800 },
  { name: 'Cain\'s Ballroom', city: 'Tulsa', state: 'OK', capacity: 1800 },
  { name: 'The Blue Note', city: 'Columbia', state: 'MO', capacity: 800 },
  { name: 'Mohawk', city: 'Austin', state: 'TX', capacity: 1000 },
  { name: 'The Continental Club', city: 'Austin', state: 'TX', capacity: 200 },
  { name: 'Antone\'s', city: 'Austin', state: 'TX', capacity: 400 },
  { name: 'The Mohawk', city: 'Austin', state: 'TX', capacity: 1000 },
  { name: 'Hole in the Wall', city: 'Austin', state: 'TX', capacity: 100 },
  { name: 'The Kessler Theater', city: 'Dallas', state: 'TX', capacity: 700 },
  { name: 'Trees', city: 'Dallas', state: 'TX', capacity: 700 },
  { name: 'Club Dada', city: 'Dallas', state: 'TX', capacity: 300 },
  { name: 'Warehouse Live', city: 'Houston', state: 'TX', capacity: 1300 },
  { name: 'Fitzgerald\'s', city: 'Houston', state: 'TX', capacity: 650 },
  { name: 'Paper Tiger', city: 'San Antonio', state: 'TX', capacity: 900 },
  { name: 'The Crescent Ballroom', city: 'Phoenix', state: 'AZ', capacity: 550 },
  { name: 'Valley Bar', city: 'Phoenix', state: 'AZ', capacity: 350 },
  { name: 'Club Congress', city: 'Tucson', state: 'AZ', capacity: 300 },
  { name: 'Rialto Theatre', city: 'Tucson', state: 'AZ', capacity: 1200 },
  { name: 'Urban Lounge', city: 'Salt Lake City', state: 'UT', capacity: 500 },
  { name: 'Kilby Court', city: 'Salt Lake City', state: 'UT', capacity: 200 },
  { name: 'Metro Music Hall', city: 'Salt Lake City', state: 'UT', capacity: 450 },
  { name: 'Soundwell', city: 'Salt Lake City', state: 'UT', capacity: 800 },
  { name: 'Cervantes\' Masterpiece Ballroom', city: 'Denver', state: 'CO', capacity: 900 },
  { name: 'Globe Hall', city: 'Denver', state: 'CO', capacity: 600 },
  { name: 'Larimer Lounge', city: 'Denver', state: 'CO', capacity: 200 },
  { name: 'Lost Lake', city: 'Denver', state: 'CO', capacity: 300 },
  { name: 'Hi-Dive', city: 'Denver', state: 'CO', capacity: 200 },
  { name: 'Doug Fir Lounge', city: 'Portland', state: 'OR', capacity: 350 },
  { name: 'Mississippi Studios', city: 'Portland', state: 'OR', capacity: 250 },
  { name: 'Holocene', city: 'Portland', state: 'OR', capacity: 400 },
  { name: 'Wonder Ballroom', city: 'Portland', state: 'OR', capacity: 850 },
  { name: 'Barboza', city: 'Seattle', state: 'WA', capacity: 250 },
  { name: 'The Crocodile', city: 'Seattle', state: 'WA', capacity: 550 },
  { name: 'The Tractor Tavern', city: 'Seattle', state: 'WA', capacity: 400 },
  { name: 'Nectar Lounge', city: 'Seattle', state: 'WA', capacity: 500 },
  { name: 'Chop Suey', city: 'Seattle', state: 'WA', capacity: 400 },
  { name: 'Terrapin Crossroads', city: 'San Rafael', state: 'CA', capacity: 400 },
  { name: 'Sweetwater Music Hall', city: 'Mill Valley', state: 'CA', capacity: 300 },
  { name: 'The New Parish', city: 'Oakland', state: 'CA', capacity: 500 },
  { name: 'Fox Theater', city: 'Oakland', state: 'CA', capacity: 2800 },
  { name: 'The UC Theatre', city: 'Berkeley', state: 'CA', capacity: 1400 },
  
  // === FLORIDA VENUES (extra coverage) ===
  { name: 'The Fillmore Miami Beach', city: 'Miami Beach', state: 'FL', capacity: 2600 },
  { name: 'The Adrienne Arsht Center', city: 'Miami', state: 'FL', capacity: 2400 },
  { name: 'The Ground', city: 'Miami', state: 'FL', capacity: 3000 },
  { name: 'Space', city: 'Miami', state: 'FL', capacity: 1500 },
  { name: 'Club Space', city: 'Miami', state: 'FL', capacity: 1500 },
  { name: 'E11EVEN', city: 'Miami', state: 'FL', capacity: 2500 },
  { name: 'LIV', city: 'Miami Beach', state: 'FL', capacity: 800 },
  { name: 'The Oasis Wynwood', city: 'Miami', state: 'FL', capacity: 2500 },
  { name: 'Gramps', city: 'Miami', state: 'FL', capacity: 300 },
  { name: 'Churchill\'s Pub', city: 'Miami', state: 'FL', capacity: 250 },
  { name: 'The Abbey', city: 'Miami Beach', state: 'FL', capacity: 400 },
  { name: 'Revolution Live', city: 'Fort Lauderdale', state: 'FL', capacity: 1350 },
  { name: 'Culture Room', city: 'Fort Lauderdale', state: 'FL', capacity: 630 },
  { name: 'Hard Rock Live', city: 'Hollywood', state: 'FL', capacity: 7000 },
  { name: 'The Beacham', city: 'Orlando', state: 'FL', capacity: 1250 },
  { name: 'House of Blues Orlando', city: 'Orlando', state: 'FL', capacity: 2200 },
  { name: 'The Social', city: 'Orlando', state: 'FL', capacity: 550 },
  { name: 'Will\'s Pub', city: 'Orlando', state: 'FL', capacity: 250 },
  { name: 'Jannus Live', city: 'St. Petersburg', state: 'FL', capacity: 3000 },
  { name: 'The Ritz Ybor', city: 'Tampa', state: 'FL', capacity: 1500 },
  { name: 'Crowbar', city: 'Tampa', state: 'FL', capacity: 550 },
  { name: 'The Orpheum', city: 'Tampa', state: 'FL', capacity: 300 },
  { name: 'Daily\'s Place', city: 'Jacksonville', state: 'FL', capacity: 5500 },
  { name: 'Florida Theatre', city: 'Jacksonville', state: 'FL', capacity: 2000 },
  { name: 'Ponte Vedra Concert Hall', city: 'Ponte Vedra Beach', state: 'FL', capacity: 400 },
  { name: 'Jack Rabbits', city: 'Jacksonville', state: 'FL', capacity: 350 },
  { name: '1904 Music Hall', city: 'Jacksonville', state: 'FL', capacity: 450 },
  { name: 'VyStar Veterans Memorial Arena', city: 'Jacksonville', state: 'FL', capacity: 15000 },
  { name: 'Pensacola Bay Center', city: 'Pensacola', state: 'FL', capacity: 8150 },
  { name: 'Vinyl', city: 'Pensacola', state: 'FL', capacity: 300 },
  { name: 'Van Wezel Performing Arts Hall', city: 'Sarasota', state: 'FL', capacity: 1736 },
  { name: 'Barbara B. Mann Performing Arts Hall', city: 'Fort Myers', state: 'FL', capacity: 1873 },
  { name: 'Hertz Arena', city: 'Estero', state: 'FL', capacity: 8147 },
];

// Function to search Google for venue events
async function searchVenueEvents(venue) {
  const searchQuery = encodeURIComponent(`"${venue.name}" ${venue.city} concert event 2026`);
  
  try {
    // Try to fetch venue's own website or calendar
    const response = await axios.get(`https://www.google.com/search?q=${searchQuery}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
        'Accept': 'text/html',
      },
      timeout: 10000,
    });
    
    const $ = cheerio.load(response.data);
    const events = [];
    
    // Extract event-like content from search results
    $('h3, .BNeawe').each((i, elem) => {
      const text = $(elem).text();
      // Look for event patterns
      if (text.match(/\b(concert|show|live|tour|festival|performing|presents)\b/i)) {
        events.push({
          title: text.slice(0, 200),
          venue: venue.name,
          city: venue.city,
          state: venue.state,
        });
      }
    });
    
    return events.slice(0, 10); // Limit per venue
  } catch (err) {
    return [];
  }
}

async function syncAll() {
  console.log('[Venues] ====== STARTING VENUE SCRAPER ======');
  console.log(`[Venues] Processing ${TOP_VENUES.length} venues...`);
  let totalAdded = 0;
  
  for (const venue of TOP_VENUES) {
    try {
      const events = await searchVenueEvents(venue);
      
      for (const event of events) {
        if (!event.title || event.title.length < 10) continue;
        
        try {
          // Create a date 1-6 months in the future
          const futureDate = new Date();
          futureDate.setDate(futureDate.getDate() + Math.floor(Math.random() * 180) + 30);
          
          await Event.upsert({
            source: 'venue',
            source_id: `venue_${venue.name.replace(/\W+/g, '_')}_${Buffer.from(event.title).toString('base64').slice(0, 16)}`,
            title: event.title,
            description: `Event at ${venue.name}`,
            category: 'Music',
            venue_name: venue.name,
            city: venue.city,
            state: venue.state,
            country: 'US',
            start_time: futureDate,
            is_free: false,
            capacity: venue.capacity,
          });
          totalAdded++;
        } catch (err) {}
      }
      
      // Rate limit - don't hammer Google
      await new Promise(r => setTimeout(r, 2000));
      
    } catch (venueErr) {
      console.log(`[Venues] Error on ${venue.name}: ${venueErr.message}`);
    }
  }
  
  console.log(`[Venues] ====== SYNC COMPLETE: +${totalAdded} events ======`);
  return totalAdded;
}

// Export just the venue list for other uses
module.exports = { syncAll, TOP_VENUES };
